---
title: "resume"
format:
  html: 
    toc: true
  pdf:
    author: Jenny L. Richmond Ph.D
    pdf-engine: weasyprint
css: ch.css
format-links: [pdf]
---

::: {.print-only .contact-block}
e: jennyrichmond\@gmail.com \| ph: +64 22-356-9846 \| w: [jenrichmond.github.io](https://jenrichmond.github.io/)
:::

## SUMMARY

Award-winning academic with 15+ years of experience mentoring university students, facilitating engaging learning experiences, and supervising research and work placement projects. Proven ability to guide students in their educational program using innovative and student-centered approaches. Dedicated to creating equitable educational experiences where students drive their own learning, expand how they see the world, and build leadership potential.


## PROFESSIONAL EXPERIENCE

### Associate Professor \| Director Academic Programs

#### School of Psychology, University of New South Wales [2019-2025]{.cvdate}

#### Academic Coaching & Mentoring

- Provided supervision and support to research students to foster academic confidence, improve scholarly work and help to build self-regulated learning skills 
- Delivered academic writing workshops to undergraduate students in person, online and via the [PsychEd podcast](https://open.spotify.com/show/5pCOyvuFSaeFaYjjIKnY3j) creating open learning resources that students can draw on throughout their studies
- Mentored tutors and casual teaching staff to create inclusive learning environments, constructive feedback mechanisms, and engaging student experiences
- Coached junior education-focused academics to design educational interventions, build evidence-based practice, and navigate career development, resulting in successful grants and promotions

#### Facilitating Learning Experiences

- Ran online and in-person learning sessions for cohorts ranging from 12 to 1,200 students using technology creatively to improve engagement and build community 
- Integrated [self-management resources](https://journals.sagepub.com/doi/full/10.1177/14757257221098763) into undergraduate courses, designing learning opportunities and assessments that promoted autonomy, competence and relatedness for learners 
- Coordinated work-integrated learning program, designing placement preparation modules that enhanced industry readiness, and growing enrollments by 50% over 2 years
- Designed and delivered monthly PSYCHEd Brown Bag sessions, facilitating ed tech and pedagogy knowledge sharing among 30+ teaching staff


#### Research & Project Supervision

- Mentored 6 PhD students and 30 Honours students through independent research projects, providing personalised guidance on research design, methodology, analysis, and academic writing
- Supervised undergraduate students undertaking workplace projects, monitoring welfare and resolving workplace expectation misalignments while ensuring learning outcomes


#### Academic Skills Development

- Strengthened core academic capacities in research design, critical thinking, and academic writing through structured undergraduate curriculum and individual coaching
- Designed and led research internship course for 3rd-year undergraduates, scaffolding the process of learning to work with real-world data and improving data literacy and analysis skills
- Designed assessments aligned with learning outcomes that built students' capacity to think critically and communicate effectively, while [learning alongside generative AI](https://journals.sagepub.com/doi/full/10.1177/00986283241287203)

#### Program Development & Collaboration

- Led strategic academic program development for 1,300+ students, collaborating with 5 program directors to align institutional goals with accreditation requirements through collaborative, data-driven decision making
- Built communities of practice that enhanced department-wide teaching expertise through knowledge sharing and peer mentorship
- Represented department on Faculty governance committees, advocating for policy initiatives that prioritised student wellbeing and success

#### Innovation & Educational Design

- Designed and implemented generative AI acknowledgement processes in assessment, balancing innovation with academic integrity through evidence-based policy development
- Integrated cultural responsiveness into curriculum, designing activities that scaffolded learning about diverse perspectives and the importance of reflexivity in psychological practice
- Led ["Postcards of Practice" project](https://www.teaching.unsw.edu.au/ai/postcards-of-practice), creating repository of generative AI use cases to facilitate knowledge sharing among teaching staff


### Lecturer \| Senior Lecturer 

#### School of Psychology, University of New South Wales [2008-2019]{.cvdate}

- Analysed behavioral and electrophysiological data using R-based pipelines, securing $430,000 in research funding through evidence-based proposals
- Authored [37 peer-reviewed publications](https://scholar.google.com/citations?hl=en&user=abDWUYwAAAAJ&view_op=list_works&sortby=pubdate), demonstrating strong understanding of research methods and academic conventions
- Created supportive lab culture fostering collaboration, peer mentorship, and knowledge sharing 

### R-Ladies Sydney Co-founder [2018-2022]{.cvdate}

-   Founded and led RLadies chapter, driving community growth to 1000+ members by organising 48+ events and workshops, focused on diversity and skill-building
-   Launched [#RYouWithMe program](https://rladiessydney.org/courses/), providing interactive tutorials and videos to 40,000+ new R users, enhancing data analysis skills
-   Developed innovative event formats (e.g., lightning talks, "shut up and code" sessions) to lower barriers to entry, improving participation

## EDUCATION

#### Doctor of Philosophy -- Psychology \| Bachelor of Science (Hons) -- Psychology (University of Otago)

#### Awards

**2024** Faculty of Science Leadership Impact Award \| **2021** Exemplary Teaching Practice Award

**2020** Faculty of Science Stand out Award \| **2019** Vice Chancellors Award for Excellence in Teaching

**2018** Faculty of Science Award for Educational Excellence
