{
  "hash": "6d07b0ec77be9c2e7e09fd0473b2da02",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: analysing smartwatch data\ndate: '2022-07-13'\nauthor:\n  - name: Jen Richmond\n    url: https://jenrichmond.github.io/\nformat: html\neditor: source\nimage: featured.png\n---\n\n\n\nSometimes trying to replicate what someone is doing in a blogpost you find on twitter is a great way to learn something new. I am half heartedly thinking about trying to learn Python so when I saw [this post about analysing smartwatch data](https://thecleverprogrammer.com/2022/05/31/smartwatch-data-analysis-using-python/) on twitter I thought that it looked like interesting data and perhaps if I tried to do what they had done in R, that would be a useful way of starting to translate my R knowledge into python... maybe. \n\nSo here we go....\n\n# load packages\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(here)\nlibrary(naniar)\nlibrary(lubridate)\nlibrary(skimr)\nlibrary(ggeasy)\nlibrary(gt)\nlibrary(janitor)\n```\n:::\n\n\n\n# read in the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- read_csv(\"dailyActivity_merged.csv\")\n```\n:::\n\n\n\n# look at the first few rows\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 15\n          Id ActivityDate TotalSteps TotalDistance TrackerDistance\n       <dbl> <chr>             <dbl>         <dbl>           <dbl>\n1 1503960366 4/12/2016         13162          8.5             8.5 \n2 1503960366 4/13/2016         10735          6.97            6.97\n3 1503960366 4/14/2016         10460          6.74            6.74\n4 1503960366 4/15/2016          9762          6.28            6.28\n5 1503960366 4/16/2016         12669          8.16            8.16\n6 1503960366 4/17/2016          9705          6.48            6.48\n# ℹ 10 more variables: LoggedActivitiesDistance <dbl>,\n#   VeryActiveDistance <dbl>, ModeratelyActiveDistance <dbl>,\n#   LightActiveDistance <dbl>, SedentaryActiveDistance <dbl>,\n#   VeryActiveMinutes <dbl>, FairlyActiveMinutes <dbl>,\n#   LightlyActiveMinutes <dbl>, SedentaryMinutes <dbl>, Calories <dbl>\n```\n\n\n:::\n:::\n\n\n\n# check if there are NAs\n\nA few ways to check NAs, the easiest uses `naniar` to visualise NAs with vis_miss()\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvis_miss(df)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\nAlternatively you can use dplyr to summarise across the whole dataframe... \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# using dplyr\ndf %>%\n  summarise(missing = sum(is.na(.)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  missing\n    <int>\n1       0\n```\n\n\n:::\n\n```{.r .cell-code}\n# or more simply w n_miss() from naniar\nn_miss(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n... or separately for each variable\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# using dplyr \ndf %>%\n  summarise_all(funs(sum(is.na(.))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 15\n     Id ActivityDate TotalSteps TotalDistance TrackerDistance\n  <int>        <int>      <int>         <int>           <int>\n1     0            0          0             0               0\n# ℹ 10 more variables: LoggedActivitiesDistance <int>,\n#   VeryActiveDistance <int>, ModeratelyActiveDistance <int>,\n#   LightActiveDistance <int>, SedentaryActiveDistance <int>,\n#   VeryActiveMinutes <int>, FairlyActiveMinutes <int>,\n#   LightlyActiveMinutes <int>, SedentaryMinutes <int>, Calories <int>\n```\n\n\n:::\n\n```{.r .cell-code}\n# or more simply w miss_var_summary() from naniar\n\nmiss_var_summary(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 3\n   variable                 n_miss pct_miss\n   <chr>                     <int>    <num>\n 1 Id                            0        0\n 2 ActivityDate                  0        0\n 3 TotalSteps                    0        0\n 4 TotalDistance                 0        0\n 5 TrackerDistance               0        0\n 6 LoggedActivitiesDistance      0        0\n 7 VeryActiveDistance            0        0\n 8 ModeratelyActiveDistance      0        0\n 9 LightActiveDistance           0        0\n10 SedentaryActiveDistance       0        0\n11 VeryActiveMinutes             0        0\n12 FairlyActiveMinutes           0        0\n13 LightlyActiveMinutes          0        0\n14 SedentaryMinutes              0        0\n15 Calories                      0        0\n```\n\n\n:::\n:::\n\n\n\nTake home message: there are no missing values in this dataset. \n\n# look at data types\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 940\nColumns: 15\n$ Id                       <dbl> 1503960366, 1503960366, 1503960366, 150396036…\n$ ActivityDate             <chr> \"4/12/2016\", \"4/13/2016\", \"4/14/2016\", \"4/15/…\n$ TotalSteps               <dbl> 13162, 10735, 10460, 9762, 12669, 9705, 13019…\n$ TotalDistance            <dbl> 8.50, 6.97, 6.74, 6.28, 8.16, 6.48, 8.59, 9.8…\n$ TrackerDistance          <dbl> 8.50, 6.97, 6.74, 6.28, 8.16, 6.48, 8.59, 9.8…\n$ LoggedActivitiesDistance <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ VeryActiveDistance       <dbl> 1.88, 1.57, 2.44, 2.14, 2.71, 3.19, 3.25, 3.5…\n$ ModeratelyActiveDistance <dbl> 0.55, 0.69, 0.40, 1.26, 0.41, 0.78, 0.64, 1.3…\n$ LightActiveDistance      <dbl> 6.06, 4.71, 3.91, 2.83, 5.04, 2.51, 4.71, 5.0…\n$ SedentaryActiveDistance  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ VeryActiveMinutes        <dbl> 25, 21, 30, 29, 36, 38, 42, 50, 28, 19, 66, 4…\n$ FairlyActiveMinutes      <dbl> 13, 19, 11, 34, 10, 20, 16, 31, 12, 8, 27, 21…\n$ LightlyActiveMinutes     <dbl> 328, 217, 181, 209, 221, 164, 233, 264, 205, …\n$ SedentaryMinutes         <dbl> 728, 776, 1218, 726, 773, 539, 1149, 775, 818…\n$ Calories                 <dbl> 1985, 1797, 1776, 1745, 1863, 1728, 1921, 203…\n```\n\n\n:::\n:::\n\n\n\nThe ActivityDate variable is characters so we need to convert that to date format\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df %>%\n  mutate(ActivityDate = mdy(ActivityDate))\n\nclass(df$ActivityDate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Date\"\n```\n\n\n:::\n:::\n\n\n\n# make a new total minutes column\n\nLets mutate a new column that sums the activity minutes. We need to use rowwise here to let R know that we want to sum those values in each row. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df %>%\n  rowwise() %>%\n  mutate(TotalMinutes = VeryActiveMinutes +FairlyActiveMinutes + LightlyActiveMinutes + SedentaryMinutes) %>%\n  ungroup()  # remember to ungroup to make sure the next operation is not rowwise\n```\n:::\n\n\n\n# descriptives\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 99) # avoid scientific notation\n\ndescriptives <- df %>%\n  select(TotalSteps:TotalMinutes) %>%\n  skim()\n\ngt(descriptives)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"abphzfxdsw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#abphzfxdsw table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#abphzfxdsw thead, #abphzfxdsw tbody, #abphzfxdsw tfoot, #abphzfxdsw tr, #abphzfxdsw td, #abphzfxdsw th {\n  border-style: none;\n}\n\n#abphzfxdsw p {\n  margin: 0;\n  padding: 0;\n}\n\n#abphzfxdsw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#abphzfxdsw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#abphzfxdsw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#abphzfxdsw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#abphzfxdsw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#abphzfxdsw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#abphzfxdsw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#abphzfxdsw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#abphzfxdsw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#abphzfxdsw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#abphzfxdsw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#abphzfxdsw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#abphzfxdsw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#abphzfxdsw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#abphzfxdsw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#abphzfxdsw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#abphzfxdsw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#abphzfxdsw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#abphzfxdsw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#abphzfxdsw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#abphzfxdsw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#abphzfxdsw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#abphzfxdsw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#abphzfxdsw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#abphzfxdsw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#abphzfxdsw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#abphzfxdsw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#abphzfxdsw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#abphzfxdsw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#abphzfxdsw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#abphzfxdsw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#abphzfxdsw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#abphzfxdsw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#abphzfxdsw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#abphzfxdsw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#abphzfxdsw .gt_left {\n  text-align: left;\n}\n\n#abphzfxdsw .gt_center {\n  text-align: center;\n}\n\n#abphzfxdsw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#abphzfxdsw .gt_font_normal {\n  font-weight: normal;\n}\n\n#abphzfxdsw .gt_font_bold {\n  font-weight: bold;\n}\n\n#abphzfxdsw .gt_font_italic {\n  font-style: italic;\n}\n\n#abphzfxdsw .gt_super {\n  font-size: 65%;\n}\n\n#abphzfxdsw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#abphzfxdsw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#abphzfxdsw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#abphzfxdsw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#abphzfxdsw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#abphzfxdsw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#abphzfxdsw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#abphzfxdsw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#abphzfxdsw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"skim_type\">skim_type</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"skim_variable\">skim_variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_missing\">n_missing</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"complete_rate\">complete_rate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"numeric.mean\">numeric.mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"numeric.sd\">numeric.sd</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"numeric.p0\">numeric.p0</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"numeric.p25\">numeric.p25</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"numeric.p50\">numeric.p50</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"numeric.p75\">numeric.p75</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"numeric.p100\">numeric.p100</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"numeric.hist\">numeric.hist</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"skim_type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"skim_variable\" class=\"gt_row gt_left\">TotalSteps</td>\n<td headers=\"n_missing\" class=\"gt_row gt_right\">0</td>\n<td headers=\"complete_rate\" class=\"gt_row gt_right\">1</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">7637.910638298</td>\n<td headers=\"numeric.sd\" class=\"gt_row gt_right\">5087.150741753</td>\n<td headers=\"numeric.p0\" class=\"gt_row gt_right\">0</td>\n<td headers=\"numeric.p25\" class=\"gt_row gt_right\">3789.750</td>\n<td headers=\"numeric.p50\" class=\"gt_row gt_right\">7405.500</td>\n<td headers=\"numeric.p75\" class=\"gt_row gt_right\">10727.0000</td>\n<td headers=\"numeric.p100\" class=\"gt_row gt_right\">36019.000000</td>\n<td headers=\"numeric.hist\" class=\"gt_row gt_left\">▇▇▁▁▁</td></tr>\n    <tr><td headers=\"skim_type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"skim_variable\" class=\"gt_row gt_left\">TotalDistance</td>\n<td headers=\"n_missing\" class=\"gt_row gt_right\">0</td>\n<td headers=\"complete_rate\" class=\"gt_row gt_right\">1</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">5.489702122</td>\n<td headers=\"numeric.sd\" class=\"gt_row gt_right\">3.924605909</td>\n<td headers=\"numeric.p0\" class=\"gt_row gt_right\">0</td>\n<td headers=\"numeric.p25\" class=\"gt_row gt_right\">2.620</td>\n<td headers=\"numeric.p50\" class=\"gt_row gt_right\">5.245</td>\n<td headers=\"numeric.p75\" class=\"gt_row gt_right\">7.7125</td>\n<td headers=\"numeric.p100\" class=\"gt_row gt_right\">28.030001</td>\n<td headers=\"numeric.hist\" class=\"gt_row gt_left\">▇▆▁▁▁</td></tr>\n    <tr><td headers=\"skim_type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"skim_variable\" class=\"gt_row gt_left\">TrackerDistance</td>\n<td headers=\"n_missing\" class=\"gt_row gt_right\">0</td>\n<td headers=\"complete_rate\" class=\"gt_row gt_right\">1</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">5.475351058</td>\n<td headers=\"numeric.sd\" class=\"gt_row gt_right\">3.907275943</td>\n<td headers=\"numeric.p0\" class=\"gt_row gt_right\">0</td>\n<td headers=\"numeric.p25\" class=\"gt_row gt_right\">2.620</td>\n<td headers=\"numeric.p50\" class=\"gt_row gt_right\">5.245</td>\n<td headers=\"numeric.p75\" class=\"gt_row gt_right\">7.7100</td>\n<td headers=\"numeric.p100\" class=\"gt_row gt_right\">28.030001</td>\n<td headers=\"numeric.hist\" class=\"gt_row gt_left\">▇▆▁▁▁</td></tr>\n    <tr><td headers=\"skim_type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"skim_variable\" class=\"gt_row gt_left\">LoggedActivitiesDistance</td>\n<td headers=\"n_missing\" class=\"gt_row gt_right\">0</td>\n<td headers=\"complete_rate\" class=\"gt_row gt_right\">1</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">0.108170940</td>\n<td headers=\"numeric.sd\" class=\"gt_row gt_right\">0.619896518</td>\n<td headers=\"numeric.p0\" class=\"gt_row gt_right\">0</td>\n<td headers=\"numeric.p25\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"numeric.p50\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"numeric.p75\" class=\"gt_row gt_right\">0.0000</td>\n<td headers=\"numeric.p100\" class=\"gt_row gt_right\">4.942142</td>\n<td headers=\"numeric.hist\" class=\"gt_row gt_left\">▇▁▁▁▁</td></tr>\n    <tr><td headers=\"skim_type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"skim_variable\" class=\"gt_row gt_left\">VeryActiveDistance</td>\n<td headers=\"n_missing\" class=\"gt_row gt_right\">0</td>\n<td headers=\"complete_rate\" class=\"gt_row gt_right\">1</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">1.502680851</td>\n<td headers=\"numeric.sd\" class=\"gt_row gt_right\">2.658941165</td>\n<td headers=\"numeric.p0\" class=\"gt_row gt_right\">0</td>\n<td headers=\"numeric.p25\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"numeric.p50\" class=\"gt_row gt_right\">0.210</td>\n<td headers=\"numeric.p75\" class=\"gt_row gt_right\">2.0525</td>\n<td headers=\"numeric.p100\" class=\"gt_row gt_right\">21.920000</td>\n<td headers=\"numeric.hist\" class=\"gt_row gt_left\">▇▁▁▁▁</td></tr>\n    <tr><td headers=\"skim_type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"skim_variable\" class=\"gt_row gt_left\">ModeratelyActiveDistance</td>\n<td headers=\"n_missing\" class=\"gt_row gt_right\">0</td>\n<td headers=\"complete_rate\" class=\"gt_row gt_right\">1</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">0.567542551</td>\n<td headers=\"numeric.sd\" class=\"gt_row gt_right\">0.883580319</td>\n<td headers=\"numeric.p0\" class=\"gt_row gt_right\">0</td>\n<td headers=\"numeric.p25\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"numeric.p50\" class=\"gt_row gt_right\">0.240</td>\n<td headers=\"numeric.p75\" class=\"gt_row gt_right\">0.8000</td>\n<td headers=\"numeric.p100\" class=\"gt_row gt_right\">6.480000</td>\n<td headers=\"numeric.hist\" class=\"gt_row gt_left\">▇▁▁▁▁</td></tr>\n    <tr><td headers=\"skim_type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"skim_variable\" class=\"gt_row gt_left\">LightActiveDistance</td>\n<td headers=\"n_missing\" class=\"gt_row gt_right\">0</td>\n<td headers=\"complete_rate\" class=\"gt_row gt_right\">1</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">3.340819149</td>\n<td headers=\"numeric.sd\" class=\"gt_row gt_right\">2.040655388</td>\n<td headers=\"numeric.p0\" class=\"gt_row gt_right\">0</td>\n<td headers=\"numeric.p25\" class=\"gt_row gt_right\">1.945</td>\n<td headers=\"numeric.p50\" class=\"gt_row gt_right\">3.365</td>\n<td headers=\"numeric.p75\" class=\"gt_row gt_right\">4.7825</td>\n<td headers=\"numeric.p100\" class=\"gt_row gt_right\">10.710000</td>\n<td headers=\"numeric.hist\" class=\"gt_row gt_left\">▆▇▆▁▁</td></tr>\n    <tr><td headers=\"skim_type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"skim_variable\" class=\"gt_row gt_left\">SedentaryActiveDistance</td>\n<td headers=\"n_missing\" class=\"gt_row gt_right\">0</td>\n<td headers=\"complete_rate\" class=\"gt_row gt_right\">1</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">0.001606383</td>\n<td headers=\"numeric.sd\" class=\"gt_row gt_right\">0.007346176</td>\n<td headers=\"numeric.p0\" class=\"gt_row gt_right\">0</td>\n<td headers=\"numeric.p25\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"numeric.p50\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"numeric.p75\" class=\"gt_row gt_right\">0.0000</td>\n<td headers=\"numeric.p100\" class=\"gt_row gt_right\">0.110000</td>\n<td headers=\"numeric.hist\" class=\"gt_row gt_left\">▇▁▁▁▁</td></tr>\n    <tr><td headers=\"skim_type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"skim_variable\" class=\"gt_row gt_left\">VeryActiveMinutes</td>\n<td headers=\"n_missing\" class=\"gt_row gt_right\">0</td>\n<td headers=\"complete_rate\" class=\"gt_row gt_right\">1</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">21.164893617</td>\n<td headers=\"numeric.sd\" class=\"gt_row gt_right\">32.844803057</td>\n<td headers=\"numeric.p0\" class=\"gt_row gt_right\">0</td>\n<td headers=\"numeric.p25\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"numeric.p50\" class=\"gt_row gt_right\">4.000</td>\n<td headers=\"numeric.p75\" class=\"gt_row gt_right\">32.0000</td>\n<td headers=\"numeric.p100\" class=\"gt_row gt_right\">210.000000</td>\n<td headers=\"numeric.hist\" class=\"gt_row gt_left\">▇▁▁▁▁</td></tr>\n    <tr><td headers=\"skim_type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"skim_variable\" class=\"gt_row gt_left\">FairlyActiveMinutes</td>\n<td headers=\"n_missing\" class=\"gt_row gt_right\">0</td>\n<td headers=\"complete_rate\" class=\"gt_row gt_right\">1</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">13.564893617</td>\n<td headers=\"numeric.sd\" class=\"gt_row gt_right\">19.987403954</td>\n<td headers=\"numeric.p0\" class=\"gt_row gt_right\">0</td>\n<td headers=\"numeric.p25\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"numeric.p50\" class=\"gt_row gt_right\">6.000</td>\n<td headers=\"numeric.p75\" class=\"gt_row gt_right\">19.0000</td>\n<td headers=\"numeric.p100\" class=\"gt_row gt_right\">143.000000</td>\n<td headers=\"numeric.hist\" class=\"gt_row gt_left\">▇▁▁▁▁</td></tr>\n    <tr><td headers=\"skim_type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"skim_variable\" class=\"gt_row gt_left\">LightlyActiveMinutes</td>\n<td headers=\"n_missing\" class=\"gt_row gt_right\">0</td>\n<td headers=\"complete_rate\" class=\"gt_row gt_right\">1</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">192.812765957</td>\n<td headers=\"numeric.sd\" class=\"gt_row gt_right\">109.174699751</td>\n<td headers=\"numeric.p0\" class=\"gt_row gt_right\">0</td>\n<td headers=\"numeric.p25\" class=\"gt_row gt_right\">127.000</td>\n<td headers=\"numeric.p50\" class=\"gt_row gt_right\">199.000</td>\n<td headers=\"numeric.p75\" class=\"gt_row gt_right\">264.0000</td>\n<td headers=\"numeric.p100\" class=\"gt_row gt_right\">518.000000</td>\n<td headers=\"numeric.hist\" class=\"gt_row gt_left\">▅▇▇▃▁</td></tr>\n    <tr><td headers=\"skim_type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"skim_variable\" class=\"gt_row gt_left\">SedentaryMinutes</td>\n<td headers=\"n_missing\" class=\"gt_row gt_right\">0</td>\n<td headers=\"complete_rate\" class=\"gt_row gt_right\">1</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">991.210638298</td>\n<td headers=\"numeric.sd\" class=\"gt_row gt_right\">301.267436790</td>\n<td headers=\"numeric.p0\" class=\"gt_row gt_right\">0</td>\n<td headers=\"numeric.p25\" class=\"gt_row gt_right\">729.750</td>\n<td headers=\"numeric.p50\" class=\"gt_row gt_right\">1057.500</td>\n<td headers=\"numeric.p75\" class=\"gt_row gt_right\">1229.5000</td>\n<td headers=\"numeric.p100\" class=\"gt_row gt_right\">1440.000000</td>\n<td headers=\"numeric.hist\" class=\"gt_row gt_left\">▁▁▇▅▇</td></tr>\n    <tr><td headers=\"skim_type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"skim_variable\" class=\"gt_row gt_left\">Calories</td>\n<td headers=\"n_missing\" class=\"gt_row gt_right\">0</td>\n<td headers=\"complete_rate\" class=\"gt_row gt_right\">1</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">2303.609574468</td>\n<td headers=\"numeric.sd\" class=\"gt_row gt_right\">718.166862134</td>\n<td headers=\"numeric.p0\" class=\"gt_row gt_right\">0</td>\n<td headers=\"numeric.p25\" class=\"gt_row gt_right\">1828.500</td>\n<td headers=\"numeric.p50\" class=\"gt_row gt_right\">2134.000</td>\n<td headers=\"numeric.p75\" class=\"gt_row gt_right\">2793.2500</td>\n<td headers=\"numeric.p100\" class=\"gt_row gt_right\">4900.000000</td>\n<td headers=\"numeric.hist\" class=\"gt_row gt_left\">▁▆▇▃▁</td></tr>\n    <tr><td headers=\"skim_type\" class=\"gt_row gt_left\">numeric</td>\n<td headers=\"skim_variable\" class=\"gt_row gt_left\">TotalMinutes</td>\n<td headers=\"n_missing\" class=\"gt_row gt_right\">0</td>\n<td headers=\"complete_rate\" class=\"gt_row gt_right\">1</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">1218.753191489</td>\n<td headers=\"numeric.sd\" class=\"gt_row gt_right\">265.931767055</td>\n<td headers=\"numeric.p0\" class=\"gt_row gt_right\">2</td>\n<td headers=\"numeric.p25\" class=\"gt_row gt_right\">989.750</td>\n<td headers=\"numeric.p50\" class=\"gt_row gt_right\">1440.000</td>\n<td headers=\"numeric.p75\" class=\"gt_row gt_right\">1440.0000</td>\n<td headers=\"numeric.p100\" class=\"gt_row gt_right\">1440.000000</td>\n<td headers=\"numeric.hist\" class=\"gt_row gt_left\">▁▁▁▅▇</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n# scatterplot\n\n## the goal \n\n![](https://i0.wp.com/thecleverprogrammer.com/wp-content/uploads/2022/05/smartwatch-1.png?w=1158&ssl=1)\n\n\nIn the python plot they use a \"ols\" trendline but I don't really know what that is so using \"lm\" instead. The graph in the post has the size of the points plotting very active minutes but there isn't a legend on the plot, so I am using a function from `ggeasy` to remove the legend. Also worked out how to make the y axis be labelled 0 - 40k, rather than 0-40000 using the labels argument in `scale_y_continuous`. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>%\n  ggplot(aes(x = Calories, y = TotalSteps, size = VeryActiveMinutes)) +\n  geom_point(colour = \"blue\", alpha = 0.5) + \n  geom_smooth(method = \"lm\", se = FALSE) +\n  easy_remove_legend() +\n  scale_y_continuous(limits = c(0,40000), labels = c(\"0\", \"10k\", \"20k\", \"30k\", \"40k\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n# pie chart\n\n## the goal\n\n![](https://i0.wp.com/thecleverprogrammer.com/wp-content/uploads/2022/05/smartwatch-2.png?w=1158&ssl=1)\n\nThe next graph in the blog post is a pie chart plotting the total active minutes in the 4 categories (inactive, lightly active, very active and fairly active). First I need to replicate these values. Luckily they are in the descriptives, so I am just going to select and filter everything else out of that dataframe.  \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntam <- descriptives %>%\n  select(skim_variable, numeric.mean) %>%\n  filter(skim_variable %in% c( \"SedentaryMinutes\", \"LightlyActiveMinutes\" , \"FairlyActiveMinutes\", \"VeryActiveMinutes\")) \n\ngt(tam)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"dggjiznwbr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dggjiznwbr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dggjiznwbr thead, #dggjiznwbr tbody, #dggjiznwbr tfoot, #dggjiznwbr tr, #dggjiznwbr td, #dggjiznwbr th {\n  border-style: none;\n}\n\n#dggjiznwbr p {\n  margin: 0;\n  padding: 0;\n}\n\n#dggjiznwbr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dggjiznwbr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dggjiznwbr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dggjiznwbr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dggjiznwbr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dggjiznwbr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dggjiznwbr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dggjiznwbr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dggjiznwbr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dggjiznwbr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dggjiznwbr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dggjiznwbr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dggjiznwbr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dggjiznwbr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dggjiznwbr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dggjiznwbr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dggjiznwbr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dggjiznwbr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dggjiznwbr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dggjiznwbr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dggjiznwbr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dggjiznwbr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dggjiznwbr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dggjiznwbr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dggjiznwbr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dggjiznwbr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dggjiznwbr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dggjiznwbr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dggjiznwbr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dggjiznwbr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dggjiznwbr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dggjiznwbr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dggjiznwbr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dggjiznwbr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dggjiznwbr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dggjiznwbr .gt_left {\n  text-align: left;\n}\n\n#dggjiznwbr .gt_center {\n  text-align: center;\n}\n\n#dggjiznwbr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dggjiznwbr .gt_font_normal {\n  font-weight: normal;\n}\n\n#dggjiznwbr .gt_font_bold {\n  font-weight: bold;\n}\n\n#dggjiznwbr .gt_font_italic {\n  font-style: italic;\n}\n\n#dggjiznwbr .gt_super {\n  font-size: 65%;\n}\n\n#dggjiznwbr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dggjiznwbr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dggjiznwbr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dggjiznwbr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dggjiznwbr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dggjiznwbr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dggjiznwbr .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#dggjiznwbr .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#dggjiznwbr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"skim_variable\">skim_variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"numeric.mean\">numeric.mean</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"skim_variable\" class=\"gt_row gt_left\">VeryActiveMinutes</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">21.16489</td></tr>\n    <tr><td headers=\"skim_variable\" class=\"gt_row gt_left\">FairlyActiveMinutes</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">13.56489</td></tr>\n    <tr><td headers=\"skim_variable\" class=\"gt_row gt_left\">LightlyActiveMinutes</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">192.81277</td></tr>\n    <tr><td headers=\"skim_variable\" class=\"gt_row gt_left\">SedentaryMinutes</td>\n<td headers=\"numeric.mean\" class=\"gt_row gt_right\">991.21064</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\nOK first thing to \"fix\" are the labels on these categories. Inactive seems like a better label than Sedentary. Make the skim variable a factor first. Then use `levels()` to check that there are now levels. Then use `fct_recode()` to change the labels on the factor levels manually. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(tam)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 4\nColumns: 2\n$ skim_variable <chr> \"VeryActiveMinutes\", \"FairlyActiveMinutes\", \"LightlyActi…\n$ numeric.mean  <dbl> 21.16489, 13.56489, 192.81277, 991.21064\n```\n\n\n:::\n\n```{.r .cell-code}\ntam <- tam %>%\n  mutate(skim_variable = as_factor(skim_variable))\n\nlevels(tam$skim_variable)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"VeryActiveMinutes\"    \"FairlyActiveMinutes\"  \"LightlyActiveMinutes\"\n[4] \"SedentaryMinutes\"    \n```\n\n\n:::\n\n```{.r .cell-code}\ntam <- tam %>%\n  mutate(skim_variable = fct_recode(skim_variable, \n                                    \"Very Active Minutes\" =  \"VeryActiveMinutes\", \n                                   \"Fairly Active Minutes\" = \"FairlyActiveMinutes\", \n                                   \"Lightly Active Minutes\" = \"LightlyActiveMinutes\", \n                                    \"Inactive Minutes\" = \"SedentaryMinutes\"))\n\nlevels(tam$skim_variable)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Very Active Minutes\"    \"Fairly Active Minutes\"  \"Lightly Active Minutes\"\n[4] \"Inactive Minutes\"      \n```\n\n\n:::\n:::\n\n\n\nThere isn't a `geom_pie()` in ggplot, probably because pie charts are the *worst visualisation* but you can make one by first making a stacked bar chart using `geom_bar()` and then adding `coord_polar()`. \n\n\nGood instructions available here https://r-graph-gallery.com/piechart-ggplot2.html\n\nBar graph version...\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntam %>%\n  ggplot(aes(x=\"\", y=numeric.mean, fill=skim_variable)) +\n  geom_bar(stat=\"identity\") \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n... add `coord_polar()`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntam %>%\n  ggplot(aes(x=\"\", y=numeric.mean, fill=skim_variable)) +\n  geom_bar(stat=\"identity\", color=\"white\") +\n  coord_polar(\"y\", start = 0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\nOK the bones are there but I really don't want the axis labels or the grey background. Add `theme_void()` to get rid of those. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntam %>%\n  ggplot(aes(x=\"\", y=numeric.mean, fill=skim_variable)) +\n  geom_bar(stat=\"identity\", color=\"white\") +\n  coord_polar(\"y\", start = 0) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\nAwesome, now in the post they have the legend ordered by the mean (with Inactive at the top). I think you can do that within a mutate, right before your data hits ggplot [see this post] (https://r-graph-gallery.com/267-reorder-a-variable-in-ggplot2.html). \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n tam %>%\n  mutate(skim_variable = fct_reorder(skim_variable, desc(numeric.mean))) %>%\n  ggplot(aes(x=\"\", y=numeric.mean, fill=skim_variable)) +\n  geom_bar(stat=\"identity\", color=\"white\") +\n  coord_polar(\"y\", start = 0) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\nAnd they have ridiculous number labels... in the spirit of reproducibility, lets do that too!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntam %>%\n  mutate(skim_variable = fct_reorder(skim_variable, desc(numeric.mean))) %>%\n  ggplot(aes(x=\"\", y=numeric.mean, fill=skim_variable, label = numeric.mean)) +\n  geom_bar(stat=\"identity\", color=\"white\") +\n  coord_polar(\"y\", start = 0) +\n  theme_void() +\n  geom_text(angle = 45)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\nHmmmm I have overlapping numbers! I would be great to have more control over where the numbers go... I thought maybe `ggannotate` would help but it doesn't work with polar coordinates. So I am stuck with position dodge. Adding a mutate to round the numbers also helps...\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntam %>%\n  mutate(skim_variable = fct_reorder(skim_variable, desc(numeric.mean))) %>%\n  mutate(numeric.mean =  round(numeric.mean, 4)) %>%\n  ggplot(aes(x=\"\", y=numeric.mean, fill=skim_variable, label = numeric.mean)) +\n  geom_bar(stat=\"identity\", color=\"white\") +\n  coord_polar(\"y\", start = 0) +\n  theme_void() +\n  geom_text(angle = 45, position = position_dodge(0.5))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\nNot terrible, what about colours?? The original post has blue, pink, yellow and green. \n\n- blue 1\t0\t245\t(#0100F5)\n- pink 246\t194\t203\t(#F6C2CB)\n- yellow 249\t217\t73\t(#F9D949)\n- green 166\t236\t153\t(#A6EC99)\n\n\nI worked out how to use the Digital Colour Meter from Utilities on my Mac ot get the exact RGB codes for the colours in the graph using [this resource](https://www.wikihow.com/Get-the-Hex-Code-of-a-Color-on-Your-Computer-Screen).\n\nThen used this [RGB-Hex converter](https://www.rgbtohex.net/). I wonder if this step is necessary?? does ggplot know RGB codes??\n\nAhhh maybe not... but there is a `rgb` function, check this out!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrgb(1,0,245, maxColorValue = 255)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"#0100F5\"\n```\n\n\n:::\n\n```{.r .cell-code}\nrgb(246,194,203, maxColorValue = 255)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"#F6C2CB\"\n```\n\n\n:::\n\n```{.r .cell-code}\nrgb(249,217,73, maxColorValue = 255)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"#F9D949\"\n```\n\n\n:::\n\n```{.r .cell-code}\nrgb(166,236,153, maxColorValue = 255)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"#A6EC99\"\n```\n\n\n:::\n:::\n\n\n\nAdding in colours using `scale_fill_manual()` and removing the legend title with `ggeasy`. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntam %>%\n  mutate(skim_variable = fct_reorder(skim_variable, desc(numeric.mean))) %>%\n  mutate(numeric.mean =  round(numeric.mean, 4)) %>%\n  ggplot(aes(x=\"\", y=numeric.mean, fill=skim_variable, label = numeric.mean)) +\n  geom_bar(stat=\"identity\", color=\"white\") +\n  scale_fill_manual(values = c(\"#0100F5\",\"#F6C2CB\",\"#F9D949\",\"#A6EC99\")) +\n  coord_polar(\"y\", start = 0) +\n  theme_void() +\n  geom_text(angle = 45, position = position_dodge(0.5)) +\n  easy_remove_legend_title()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\n\nUnder the pie chart there are some summary stats...lets see if we can get those using inline code.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntam_wide <- tam %>%\n  pivot_wider(names_from = skim_variable, values_from = numeric.mean) %>%\n  clean_names() %>%\n  rowwise() %>%\n  mutate(total = very_active_minutes + fairly_active_minutes + lightly_active_minutes + inactive_minutes) %>%\n  pivot_longer(names_to = \"category\", values_to = \"minutes\", very_active_minutes:inactive_minutes) %>%\n  relocate(total, .after = minutes) %>%\n  mutate(percent = (minutes/total)*100) %>%\n  mutate(percent = round(percent, 1)) %>%\n   mutate(minutes = round(minutes, 0))\n```\n:::\n\n\n\n\n**Observations**\n\n1. 81.3 of Total inactive minutes in a day\n2. 15.8 of Lightly active minutes in a day\n3. On an average, only 21 (1.7) were very active\n4. and 1.1 (14) of fairly active minutes in a day \n\n\n# column graph\n\n## the goal\n\n![](https://i0.wp.com/thecleverprogrammer.com/wp-content/uploads/2022/05/smartwatch-3.png?w=1158&ssl=1)\n\nNext up there is a column plot that looks at activity by day of the week. The `lubridate` package makes it easy to pull the day out of a date. I am going back to the original data frame and making a new one that includes just the id and activity date and the activity in minutes.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 940\nColumns: 16\n$ Id                       <dbl> 1503960366, 1503960366, 1503960366, 150396036…\n$ ActivityDate             <date> 2016-04-12, 2016-04-13, 2016-04-14, 2016-04-…\n$ TotalSteps               <dbl> 13162, 10735, 10460, 9762, 12669, 9705, 13019…\n$ TotalDistance            <dbl> 8.50, 6.97, 6.74, 6.28, 8.16, 6.48, 8.59, 9.8…\n$ TrackerDistance          <dbl> 8.50, 6.97, 6.74, 6.28, 8.16, 6.48, 8.59, 9.8…\n$ LoggedActivitiesDistance <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ VeryActiveDistance       <dbl> 1.88, 1.57, 2.44, 2.14, 2.71, 3.19, 3.25, 3.5…\n$ ModeratelyActiveDistance <dbl> 0.55, 0.69, 0.40, 1.26, 0.41, 0.78, 0.64, 1.3…\n$ LightActiveDistance      <dbl> 6.06, 4.71, 3.91, 2.83, 5.04, 2.51, 4.71, 5.0…\n$ SedentaryActiveDistance  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ VeryActiveMinutes        <dbl> 25, 21, 30, 29, 36, 38, 42, 50, 28, 19, 66, 4…\n$ FairlyActiveMinutes      <dbl> 13, 19, 11, 34, 10, 20, 16, 31, 12, 8, 27, 21…\n$ LightlyActiveMinutes     <dbl> 328, 217, 181, 209, 221, 164, 233, 264, 205, …\n$ SedentaryMinutes         <dbl> 728, 776, 1218, 726, 773, 539, 1149, 775, 818…\n$ Calories                 <dbl> 1985, 1797, 1776, 1745, 1863, 1728, 1921, 203…\n$ TotalMinutes             <dbl> 1094, 1033, 1440, 998, 1040, 761, 1440, 1120,…\n```\n\n\n:::\n\n```{.r .cell-code}\nday <- df %>%\n  clean_names() %>%\n  select(id:activity_date, very_active_minutes:calories) %>%\n  mutate(day = wday(activity_date, label = TRUE)) %>%\n  rename(inactive_minutes = sedentary_minutes) %>%\n  pivot_longer(names_to = \"category\", values_to = \"minutes\", very_active_minutes:inactive_minutes) %>%\n  mutate(category = str_sub(category, end = -9)) %>%\n  mutate(category = fct_relevel(category, c(\"very_active\", \"fairly_active\", \"lightly_active\", \"inactive\")))\n\nday %>%\n  filter(category != \"inactive\") %>%\n  group_by(day, category) %>%\n  summarise(activity = sum(minutes)) %>%\n  ggplot(aes(x = day, y = activity, fill = category)) +\n  geom_col(position = \"dodge\") +\n   scale_fill_manual(values = c(\"purple\", \"darkgreen\", \"pink\")) +\n   scale_y_continuous(limits = c(0,40000), labels = c(\"0\", \"10k\", \"20k\", \"30k\", \"40k\")) +\n  easy_remove_legend_title()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'day'. You can override using the `.groups`\nargument.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}